### ISSUE TITLE
Docker 1.13.1 does not like -u "wiki:3031;/wiki"

### ISSUE THREAD

**Issue by JohnMasinter** [dperson/moinmoin#10]
Hello D,
First, thank you for publishing this container! It is a great time saver.
I am running the std docker.io/nginx, configured and linked to your wiki container.
I am using Docker 1.13.1 and it does not accept -u "wiki:3031;/wiki"
When I run nginx without, it seems to work, /wiki pulls up moinmoin,
but I have not gone any further than just pulling up the initial empty page.
Do you think it's needed? Is there an alternate way to specify this to docker?
--John

**Comment by dperson** [comment]
I wrote a NGINX container as well that I also use. It has a *lot* of options to quickly configure many options and proxy connections (`-u` is a UWSGI proxy). It's available on dockerhub as `dperson/nginx` or you can read through the documentation for NGINX or the script that does the configuration at [https://github.com/dperson/nginx](https://github.com/dperson/nginx).
