### ISSUE TITLE
Can't change the prefix to '/'

### ISSUE THREAD

**Issue by oren** [dperson/moinmoin#2]
I get '403 Forbidden' when i try to change the prefix to '/'

```
docker run -e PREFIX=/ --name wiki -d -v /srv/moinmoin:/usr/local/share/moin/data dperson/moinmoin                                                                           
docker run --name web --link wiki:wiki -p 80:80 -p 443:443 -d dperson/nginx -u "wiki:3031;/"
```

**Comment by dperson** [comment]
I haven't tried to change the prefix to '/' before... I'm not sure if it's moin or nginx that's throwing the error, I'll play with it this weekend, and try to work it out for you.

**Comment by oren** [comment]
:+1:

**Comment by dperson** [comment]
It was actually a SNAFU in the nginx entrypoint script. I've updated it in github repo, but docker's build bot keeps building the container with the old version of the script. I've submitted a support ticket to docker, and hope to have it resolved shortly...

**Comment by dperson** [comment]
Okay the script is fixed (and it was actually a bug in my distros package of docker 1.6, sigh). That's out of the way.

Now, if you run the commands you used at the start (after 'docker pull' ing the new images), they'll work for you. Or at least they did when I just tested them.
