### ISSUE TITLE
Problem with Benchmarking Dockerized applications

### ISSUE THREAD

**Issue by Harrison-John** [dperson/moinmoin#3]
Hi David, Could you please help me and can guide me that how can I benchmark dockerize applications using phoronix-tesing-suite. I am desparately looking for help. Regards.

**Comment by dperson** [comment]
What this container does is create a PTS (Phoronix Test Suite) installation in a docker container. It doesn't really test applications in other containers... or arbitrary applications, just what PTS provides. Also, I really haven't tried to make any provision for running tests that require a GUI or audio.

As for how to use the PTS, that's beyond the scope of creating this container, please see the upstream documentation (http://phoronix-test-suite.com/).
