### ISSUE TITLE
werkzeug BrokenFilesystemWarning

### ISSUE THREAD

**Issue by berney** [dperson/moinmoin#5]
I see errors about BrokenFilesystemWarning. It turns out it's related to the locale not being setup. Python defaults to saying the filesystem is ASCII and Werkzeug takes issue with that an insists its UTF-8. See http://werkzeug.pocoo.org/docs/0.11/unicode/#filesystem-encoding.

The solution is to setup the locale, I have just set environment vars:

```yaml
environment:
  LANG: C.UTF-8
  LC_ALL: C_UTF-8
```

That has fixed the error, everything seems happy.

You can probably put some default ENVs in the Dockerfile or document that they should be set when running the image, e.g. in `docker-compose.yml` or `docker run` command.

Alternatively you can `apt-get install locales` and possibly `locales-all` and use `locale-gen` etc. but I think that's too much. Then again this is using Debian and not Alpine... so it's not like it's minimal.

**Comment by dperson** [comment]
Okay, if `LANG` is unset, it will now be set to `en_US.UTF-8`. Thanks for the report.

**Comment by berney** [comment]
NP, thanks for adding a fix.
