### ISSUE TITLE
1.9.9 patch not being applied properly

### ISSUE THREAD

**Issue by ducksauz** [dperson/moinmoin#6]
David,

I'm building a alpine based image for moinmoin and lovingly stealing the moinmoin install from your Dockerfile. I've found that you're not applying the patch properly, as it was hanging on me in my interactive testing. I grabbed your latest image to confirm, and the patch is definitely not getting applied in your image.

```
% docker run -it dperson/moinmoin:latest /bin/bash
root@fa096eb7ed8a:/# cd /usr/local/lib/python2.7/dist-packages/MoinMoin/
root@fa096eb7ed8a:/usr/local/lib/python2.7/dist-packages/MoinMoin# grep digestmod user.py
root@fa096eb7ed8a:/usr/local/lib/python2.7/dist-packages/MoinMoin# grep hashlib user.py
import hashlib
        hash = hashlib.new('sha1', pwd)
                        hash = hashlib.new('sha1', password.encode('utf-8'))
                            hashlib.new('sha1', password.encode('utf-8')).digest()).rstrip()
root@fa096eb7ed8a:/usr/local/lib/python2.7/dist-packages/MoinMoin# grep hmac.new user.py
        h = hmac.new(key, msg).hexdigest()
        h = hmac.new(str(self.recoverpass_key), str(stamp)).hexdigest()
```

Also, looking at your docker build logs, I don't see the patches getting applied there.

You need to replace:
```
patch -p0 ../raw
```
in your Dockerfile with:
```
patch -p1 < ../raw
```

**Comment by ducksauz** [comment]
PR: https://github.com/dperson/moinmoin/pull/7

**Comment by dperson** [comment]
Thank you for the report.
