### ISSUE TITLE
Problem when prefix=/

### ISSUE THREAD

**Issue by wd** [dperson/moinmoin#8]
When setting `PREFIX=/`, the wiki not work probably. It was caused by the wrong `url_prefix_static` settings。

    # If you run your wiki script at the root of your site (/), just do NOT
    # use this setting and it will automatically work.

In Dockerfile: 
```
   sed -e '/logo_string/ { s/moinmoin/docker/; s/MoinMoin // }' \
                -e '/url_prefix_static/ {s/#\(url_prefix_static\)/\1/; s/my//}'\
.....
```

**Comment by dperson** [comment]
I'm not sure that I follow your intent in this bug report? The wiki works, I'm not setting PREFIX=/ in my Dockerfile...

**Comment by wd** [comment]
As mentioned in readme:
```
PREFIX - An above, set a URI where the app lives, IE /wiki2
```
So we can use `PREFIX` to change the url when visit moinmoin. I've tried to set `PREFIX=/`, but css and js files not work probably, after some test , like my first post said, it was caused by the wrong `url_prefix_static` setting, If we want to run moinmoin without a prefix, we should not set `url_prefix_static` .

**Comment by 9600** [comment]
This is still a problem. If I set env var PREFIX=/ I get the config line:

url_prefix_static = '/' + url_prefix_static

And a skeletal site with CSS etc. loads. If I comment out the above and restart, all is fine.

**Comment by dperson** [comment]
Okay, I think that I found the issue. I missed it the first time through. My apologies to you both.
